# **EDA Notebook**

---
## 0. Setup Environment

In [1]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 41.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 40.0 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [2]:
group_name = "group 24"
student_name = "Shameel Zeshan Khader Sheriff"
student_id = "26030371"

In [3]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [4]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [5]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [6]:
# No aditional package required

### 0.b Import Packages

In [7]:
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [8]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "product_cost_history.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [9]:
df.head()

,product_id,start_date,end_date,standard_cost
0,05385566-38df-4855-94a8-786cae6ffe49,2011-05-31 00:00:00,2012-05-29 00:00:00,12.0278
1,05385566-38df-4855-94a8-786cae6ffe49,2012-05-30 00:00:00,2013-05-29 00:00:00,13.8782
2,05385566-38df-4855-94a8-786cae6ffe49,2013-05-30 00:00:00,NaN,13.0863
3,f33d8a41-b92f-4f2a-8f75-76ea2f25722b,2011-05-31 00:00:00,2012-05-29 00:00:00,12.0278
4,f33d8a41-b92f-4f2a-8f75-76ea2f25722b,2012-05-30 00:00:00,2013-05-29 00:00:00,13.8782

In [10]:
df.shape

(395, 4)

In [11]:
df.size

1580

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     395 non-null    object
 1   start_date     395 non-null    object
 2   end_date       200 non-null    object
 3   standard_cost  395 non-null    float64
dtypes: float64(1), object(3)
memory usage: 12.5+ KB

In [13]:
df.describe(include="all")

,product_id,start_date,end_date,standard_cost
count,395,395,200,395.000000
unique,293,3,2,NaN
top,cd05611d-d748-4820-a676-0e2ac4c0152c,2013-05-30 00:00:00,2013-05-29 00:00:00,NaN
freq,3,195,128,NaN
mean,NaN,NaN,NaN,434.265829
std,NaN,NaN,NaN,497.379884
min,NaN,NaN,NaN,0.856500
25%,NaN,NaN,NaN,37.120900
50%,NaN,NaN,NaN,204.625100
75%,NaN,NaN,NaN,660.914200
max,NaN,NaN,NaN,2171.294200

In [14]:
df.isnull().sum().sort_values(ascending=False)

end_date         195
product_id         0
start_date         0
standard_cost      0
dtype: int64

In [15]:
df.nunique().sort_values(ascending=False)

product_id       293
standard_cost    134
start_date         3
end_date           2
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
dataset_insights = """
The product_cost_history dataset contains 395 rows and 4 columns.
Each row represents a product's standard cost during a specific time period, identified by product_id, start_date, end_date, and standard_cost.

The dataset includes 293 unique products and 134 unique standard cost values.
The start_date column has 3 unique values, while end_date has 2 unique non-null values.
This suggests that the dataset records cost changes across a small number of historical cost periods.

There are no missing values in product_id, start_date, or standard_cost.
However, end_date has 195 missing values. These missing values are likely meaningful because a missing end_date usually indicates the current or active cost record for that product.
Therefore, these rows should not be removed without careful consideration.

The standard_cost column ranges from approximately 0.86 to 2171.29, with a mean of about 434.27 and a median of about 204.63.
This shows a wide spread in product costs, which is expected because the retailer sells products with very different price and cost levels.
There are no duplicate rows, so the dataset is clean from a duplicate-record perspective.

For clustering, this dataset is useful because it can support cost-related features such as current standard cost, average cost, cost range, and cost volatility.
These features can help distinguish low-cost accessories from higher-cost products such as bikes or major components.
"""

In [18]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `standard_cost`

In [19]:
# Explore feature of interest: standard_cost
feature_name = "standard_cost"

df[[feature_name]].describe()

       standard_cost
count     395.000000
mean      434.265829
std       497.379884
min         0.856500
25%        37.120900
50%       204.625100
75%       660.914200
max      2171.294200

In [20]:
alt.Chart(df).mark_bar().encode(
    x=alt.X(
        "standard_cost:Q",
        bin=alt.Bin(maxbins=30),
        title="Standard Cost"
    ),
    y=alt.Y("count():Q", title="Number of Cost Records"),
    tooltip=["count()"]
).properties(
    title="Distribution of Standard Cost Records",
    width=550,
    height=300
)

alt.Chart(...)

In [21]:
df[["product_id", "start_date", "end_date", "standard_cost"]].sort_values(
    "standard_cost",
    ascending=False
).head(10)

,product_id,start_date,end_date,standard_cost
98,41b7b226-20ea-488a-b519-b4ca65d4a64e,2011-05-31 00:00:00,2012-05-29 00:00:00,2171.2942
99,e909a64f-f56c-4f3c-b802-f539d52f8f21,2011-05-31 00:00:00,2012-05-29 00:00:00,2171.2942
102,01225971-c68c-4650-8d3c-f498ece3c5da,2011-05-31 00:00:00,2012-05-29 00:00:00,2171.2942
100,e8c12ae4-8042-4b77-8bd7-023d46440e33,2011-05-31 00:00:00,2012-05-29 00:00:00,2171.2942
101,378b5732-eba9-46e4-a6c1-4040717835d5,2011-05-31 00:00:00,2012-05-29 00:00:00,2171.2942
132,a16ed5b0-74c7-4812-adea-04b4abfd72c7,2011-05-31 00:00:00,2012-05-29 00:00:00,1912.1544
133,a8fcee30-f73d-42fb-a1bb-95d5e9e66a86,2011-05-31 00:00:00,2012-05-29 00:00:00,1912.1544
134,6cc3d977-da73-4856-b1ca-8a2f0b57b60b,2011-05-31 00:00:00,2012-05-29 00:00:00,1912.1544
135,5b78ca64-7982-49f2-8ec0-4e6bbfd5450e,2011-05-31 00:00:00,2012-05-29 00:00:00,1912.1544
139,de8b1961-ea0e-4639-9482-7f71b3ed07d8,2011-05-31 00:00:00,2012-05-29 00:00:00,1898.0944

In [22]:
feature_1_insights = """
The first feature explored is standard_cost, which represents the recorded product cost for a historical cost period. This feature is important for the selected product segmentation use case because cost helps describe the commercial profile of a product when combined with price, demand, and promotion information.

The standard_cost values range from approximately 0.86 to 2171.29. The mean cost is about 434.27, while the median cost is about 204.63. The higher mean compared with the median, together with the histogram, indicates a right-skewed distribution with many lower-cost records and a smaller number of high-cost records.

The highest cost-history records are above 1900 and 2100, showing that some products have much larger cost values than the majority of records. This wide spread is expected in a retailer selling products with different commercial roles, but it also means cost features must be handled carefully in distance-based clustering.

For later product-level modelling, standard_cost should not be joined directly from the history table without deciding how to represent it at one row per product. Suitable product-level features may include the latest available cost, average historical cost, cost range, or number of observed cost records. Monetary cost features may also require scaling and skew-aware treatment during modelling so that high-cost products do not dominate the clustering distance space.
"""

In [23]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

### B.3 Explore Feature of Interest `end_date`

In [24]:
# Create parsed date copy for cost-period analysis
cost_history_df = df.copy()

cost_history_df["start_date"] = pd.to_datetime(
    cost_history_df["start_date"],
    errors="coerce"
)

cost_history_df["end_date"] = pd.to_datetime(
    cost_history_df["end_date"],
    errors="coerce"
)

cost_history_df["is_current_cost_record"] = cost_history_df["end_date"].isna()

cost_history_df["is_current_cost_record"].value_counts()

is_current_cost_record
False    200
True     195
Name: count, dtype: int64

In [25]:
cost_period_summary = (
    cost_history_df
    .groupby(["start_date", "is_current_cost_record"], as_index=False)
    .agg(
        cost_record_count=("product_id", "count"),
        product_count=("product_id", "nunique")
    )
)

cost_period_summary

  start_date  is_current_cost_record  cost_record_count  product_count
0 2011-05-31                   False                 72             72
1 2012-05-30                   False                128            128
2 2013-05-30                    True                195            195

In [26]:
alt.Chart(cost_period_summary).mark_bar().encode(
    x=alt.X("start_date:T", title="Cost Period Start Date"),
    y=alt.Y("cost_record_count:Q", title="Number of Cost Records"),
    color=alt.Color(
        "is_current_cost_record:N",
        title="Current Cost Record"
    ),
    tooltip=[
        "start_date",
        "is_current_cost_record",
        "cost_record_count",
        "product_count"
    ]
).properties(
    title="Cost History Records by Start Period",
    width=550,
    height=300
)

alt.Chart(...)

In [27]:
feature_2_insights = """
The second feature explored is end_date because its missingness has business meaning in a product cost history table. In this dataset, 200 cost-history records have a populated end_date, while 195 records have a missing end_date.

The start-period summary shows a clear structure. The 72 records starting on 2011-05-31 and the 128 records starting on 2012-05-30 have closed cost periods with end dates. In contrast, all 195 records starting on 2013-05-30 have no end date and are marked as current cost records.

This pattern indicates that missing end_date values are not ordinary missing-data errors. They represent open or active cost records for products whose latest observed cost period has not been closed in the extract. Therefore, these rows should be retained and interpreted carefully during data preparation.

For the selected product segmentation use case, this distinction matters because end_date can help identify current/open cost records when deriving product-level cost features. However, the raw date fields should not be used directly as clustering features without a clear business transformation."""

In [28]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

### B.4 Explore Feature of Interest `cost_history_count`

In [29]:
# Aggregate historical cost records to product level
product_cost_summary = (
    cost_history_df
    .groupby("product_id", as_index=False)
    .agg(
        cost_history_count=("standard_cost", "count"),
        min_standard_cost=("standard_cost", "min"),
        max_standard_cost=("standard_cost", "max"),
        avg_standard_cost=("standard_cost", "mean"),
        first_cost_start_date=("start_date", "min"),
        latest_cost_start_date=("start_date", "max")
    )
)

product_cost_summary["standard_cost_range"] = (
    product_cost_summary["max_standard_cost"] -
    product_cost_summary["min_standard_cost"]
)

product_cost_summary.head()

,product_id,cost_history_count,min_standard_cost,max_standard_cost,avg_standard_cost,first_cost_start_date,latest_cost_start_date,standard_cost_range
0,001a3a89-15cc-435e-89e5-0c844f44f595,1,30.9334,30.9334,30.9334,2012-05-30,2012-05-30,0.000
1,0025c2c9-855d-45a7-92ad-f4ab2fb016d1,2,300.1188,360.9428,330.5308,2012-05-30,2013-05-30,60.824
2,00b509f3-14e1-42ce-b59f-07b5dd91229d,1,699.0928,699.0928,699.0928,2011-05-31,2011-05-31,0.000
3,00d697bd-e064-4e0a-8486-c04f6a4377c3,1,199.8519,199.8519,199.8519,2013-05-30,2013-05-30,0.000
4,01225971-c68c-4650-8d3c-f498ece3c5da,1,2171.2942,2171.2942,2171.2942,2011-05-31,2011-05-31,0.000

In [30]:
cost_history_count_distribution = (
    product_cost_summary["cost_history_count"]
    .value_counts()
    .sort_index()
    .reset_index()
)

cost_history_count_distribution.columns = [
    "cost_history_count",
    "product_count"
]

cost_history_count_distribution

   cost_history_count  product_count
0                   1            216
1                   2             52
2                   3             25

In [31]:
alt.Chart(cost_history_count_distribution).mark_bar().encode(
    x=alt.X("cost_history_count:O", title="Cost Records per Product"),
    y=alt.Y("product_count:Q", title="Number of Products"),
    tooltip=["cost_history_count", "product_count"]
).properties(
    title="Distribution of Cost History Records per Product",
    width=450,
    height=300
)

alt.Chart(...)

In [32]:
product_cost_summary["standard_cost_range"].describe()

count    293.000000
mean      20.943398
std       49.224547
min        0.000000
25%        0.000000
50%        0.000000
75%        1.692600
max      234.264100
Name: standard_cost_range, dtype: float64

In [33]:
feature_3_insights = """
The third feature explored is cost_history_count, which measures how many historical cost records are available for each product after summarising the cost history table to product level.

The product-level summary contains 293 unique products. Of these, 216 products have only 1 cost-history record, 52 products have 2 records, and 25 products have 3 records. This confirms that product_cost_history is not already at one row per product and that some products appear repeatedly because their standard cost is tracked across historical periods.

The standard_cost_range feature gives an additional view of observed cost variation over time. The median cost range is 0, meaning at least half of the products show no cost change within the available history records. However, the maximum range is approximately 234.26, showing that a smaller group of products experienced larger cost movement.

This relationship is important for product clustering because raw cost-history rows cannot be used directly in a one-row-per-product modelling table. Instead, the history should be represented through product-level features such as latest available standard cost, average standard cost, cost_history_count, and standard_cost_range, depending on the business purpose and available cost coverage.
"""

In [34]:
# Do not modify this code
print_tile(size="h3", key='feature_3_insights', value=feature_3_insights)

### Integration Analysis: Cost History Coverage for Products Sold

In [35]:
try:
    product_df = pd.read_csv(at.folder_path / "product.csv")
    sales_order_detail_df = pd.read_csv(at.folder_path / "sales_order_detail.csv")
except Exception as e:
    print(e)

In [36]:
print("product_cost_history rows:", len(df))
print("Unique product_id-start_date pairs:", df.drop_duplicates(["product_id", "start_date"]).shape[0])
print("Duplicate product_id-start_date records:", df.duplicated(["product_id", "start_date"]).sum())
print("Unique products in product_cost_history:", df["product_id"].nunique())

print("\nproduct rows before duplicate removal:", len(product_df))
print("Unique product_id in product:", product_df["product_id"].nunique())
print("Exact duplicate product rows:", product_df.duplicated().sum())

print("\nsales_order_detail rows:", len(sales_order_detail_df))
print("Unique sold products in sales_order_detail:", sales_order_detail_df["product_id"].nunique())

product_cost_history rows: 395
Unique product_id-start_date pairs: 395
Duplicate product_id-start_date records: 0
Unique products in product_cost_history: 293

product rows before duplicate removal: 886
Unique product_id in product: 504
Exact duplicate product rows: 382

sales_order_detail rows: 42100
Unique sold products in sales_order_detail: 254

In [37]:
product_unique_df = product_df.drop_duplicates().copy()

sold_product_ids = set(sales_order_detail_df["product_id"])
cost_history_product_ids = set(cost_history_df["product_id"])
current_cost_product_ids = set(
    cost_history_df.loc[
        cost_history_df["is_current_cost_record"],
        "product_id"
    ]
)

print("Sold products with any cost history:", len(sold_product_ids & cost_history_product_ids))
print("Sold products with current open cost record:", len(sold_product_ids & current_cost_product_ids))
print("Total sold products:", len(sold_product_ids))

Sold products with any cost history: 254
Sold products with current open cost record: 183
Total sold products: 254

In [40]:
cost_history_integration_insights = """
The product_cost_history table was checked against product and sales_order_detail to understand its usefulness for the selected sold-product clustering use case.

The history-table grain is confirmed by the record key check. product_cost_history contains 395 rows and 395 unique product_id-start_date pairs, with no duplicate records at that level. This means each row represents a product cost record for an effective start period rather than a single product row.

The product table requires care before integration because it contains 886 rows but only 504 unique product_id values, with 382 exact duplicate rows. These are exact duplicate records, so they should be removed before using product as a one-row-per-product dimension in later preparation work.

The sold-product coverage check shows that all 254 products observed in sales_order_detail have at least one record in product_cost_history. However, only 183 of those sold products have an open cost record with a missing end_date. Therefore, the cost history table has complete historical cost coverage for sold products, but incomplete current/open cost coverage.

This distinction is important for modelling. product.standard_cost is the better primary product-level cost feature because it aligns directly with the one-row-per-product modelling grain after exact duplicate product rows are removed. In contrast, product_cost_history should not be joined directly into the clustering dataset because it can contain multiple records per product. It is more suitable for derived historical cost features such as cost_history_count, average historical cost, and standard_cost_range.

Overall, product_cost_history is useful for describing historical cost behaviour, while product.standard_cost is more suitable as the main cost snapshot for the sold-product clustering dataset.
"""

In [41]:
print_tile(
    size="h3",
    key="cost_history_integration_insights",
    value=cost_history_integration_insights
)