# **EDA Notebook**

---
## 0. Setup Environment

In [3]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [4]:
group_name = "group 24"
student_name = "Shameel Zeshan Khader Sheriff"
student_id = "26030371"

In [5]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [6]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [7]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [8]:
# No aditional package required

### 0.b Import Packages

In [9]:
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [10]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "sales_territory.csv")
except Exception as e:
  print(e)

In [11]:
# Preview the dataset
df

,territory_id,name,CountryRegionCode,group,sales_ytd,sales_last_year,cost_ytd,cost_last_year
0,0ad4c625-bb65-4376-8a41-0a65719b0db8,France,FR,Europe,4.772398e+06,2.396540e+06,0.0,0.0
1,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,Germany,DE,Europe,3.805202e+06,1.307950e+06,0.0,0.0
2,2ac923e9-3043-4f5e-bae0-ad28089bf187,Australia,AU,Pacific,5.977815e+06,2.278549e+06,0.0,0.0
3,e0e3bac4-790e-4617-84b3-be0c2bdb7070,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,0.0,0.0

In [12]:
df.shape

(4, 8)

In [13]:
df.size

32

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   territory_id       4 non-null      object
 1   name               4 non-null      object
 2   CountryRegionCode  4 non-null      object
 3   group              4 non-null      object
 4   sales_ytd          4 non-null      float64
 5   sales_last_year    4 non-null      float64
 6   cost_ytd           4 non-null      float64
 7   cost_last_year     4 non-null      float64
dtypes: float64(4), object(4)
memory usage: 388.0+ bytes

In [15]:
df.describe()

          sales_ytd  sales_last_year  cost_ytd  cost_last_year
count  4.000000e+00     4.000000e+00       4.0             4.0
mean   4.892080e+06     1.904715e+06       0.0             0.0
std    8.923837e+05     5.196392e+05       0.0             0.0
min    3.805202e+06     1.307950e+06       0.0             0.0
25%    4.530599e+06     1.553855e+06       0.0             0.0
50%    4.892652e+06     1.957186e+06       0.0             0.0
75%    5.254133e+06     2.308047e+06       0.0             0.0
max    5.977815e+06     2.396540e+06       0.0             0.0

In [16]:
df.isnull().sum().sort_values(ascending=False)

territory_id         0
name                 0
CountryRegionCode    0
group                0
sales_ytd            0
sales_last_year      0
cost_ytd             0
cost_last_year       0
dtype: int64

In [17]:
df.nunique().sort_values(ascending=False)

territory_id         4
name                 4
CountryRegionCode    4
sales_ytd            4
sales_last_year      4
group                2
cost_ytd             1
cost_last_year       1
dtype: int64

### B.1 Explore Dataset

In [18]:
# Basic dataset overview
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nDataset information:")
display(df.info())

print("\nMissing values by column:")
display(df.isna().sum().to_frame("missing_values"))

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nSummary statistics:")
display(df.describe(include="all").T)

Dataset shape: (4, 8)

Column names:
['territory_id', 'name', 'CountryRegionCode', 'group', 'sales_ytd', 'sales_last_year', 'cost_ytd', 'cost_last_year']

First 5 rows:

,territory_id,name,CountryRegionCode,group,sales_ytd,sales_last_year,cost_ytd,cost_last_year
0,0ad4c625-bb65-4376-8a41-0a65719b0db8,France,FR,Europe,4.772398e+06,2.396540e+06,0.0,0.0
1,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,Germany,DE,Europe,3.805202e+06,1.307950e+06,0.0,0.0
2,2ac923e9-3043-4f5e-bae0-ad28089bf187,Australia,AU,Pacific,5.977815e+06,2.278549e+06,0.0,0.0
3,e0e3bac4-790e-4617-84b3-be0c2bdb7070,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,0.0,0.0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   territory_id       4 non-null      object
 1   name               4 non-null      object
 2   CountryRegionCode  4 non-null      object
 3   group              4 non-null      object
 4   sales_ytd          4 non-null      float64
 5   sales_last_year    4 non-null      float64
 6   cost_ytd           4 non-null      float64
 7   cost_last_year     4 non-null      float64
dtypes: float64(4), object(4)
memory usage: 388.0+ bytes

None

Missing values by column:

                   missing_values
territory_id                    0
name                            0
CountryRegionCode               0
group                           0
sales_ytd                       0
sales_last_year                 0
cost_ytd                        0
cost_last_year                  0

Duplicate rows:
0

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
territory_id,4,4,0ad4c625-bb65-4376-8a41-0a65719b0db8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,4,4,France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CountryRegionCode,4,4,FR,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group,4,2,Europe,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sales_ytd,4.0,NaN,NaN,NaN,4892080.23415,892383.664461,3805202.3478,4530599.3178,4892651.8367,5254132.75305,5977814.9154
sales_last_year,4.0,NaN,NaN,NaN,1904715.481525,519639.248459,1307949.7917,1553854.99545,1957186.18715,2308046.673225,2396539.7601
cost_ytd,4.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cost_last_year,4.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
dataset_insights = """
The sales_territory dataset contains 4 rows and 8 columns, where each row represents one sales territory.
The dataset includes territory identifiers, territory names, country or region codes, territory group, current year sales, last year sales, and cost-related fields.

The dataset is very small, so it is more useful as a descriptive or supporting table rather than a standalone modelling dataset.
There are no missing values and no duplicate rows, which means the dataset is clean from a basic data quality perspective.
The categorical columns are territory_id, name, CountryRegionCode, and group, while the numerical columns are sales_ytd, sales_last_year, cost_ytd, and cost_last_year.

The sales_ytd and sales_last_year columns show variation across territories, so they can provide useful information about regional sales performance.
However, cost_ytd and cost_last_year are both zero for all territories, meaning these fields have no variation and are not useful for modelling or clustering.
Overall, this dataset can help understand geographic sales context, but it should be combined with other datasets such as sales orders, customers, products, and offers for a stronger clustering model.

This table may support geographic context if territory-based product features are
later engineered from sales-order data. However, it is not selected as the main
clustering base because it contains only four territory records and its join to
sales_order_header covers only part of the order data.
"""

In [20]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `sales_ytd`

In [21]:
# Explore feature of interest: sales_ytd
feature_name = "sales_ytd"

df[[feature_name]].describe()

          sales_ytd
count  4.000000e+00
mean   4.892080e+06
std    8.923837e+05
min    3.805202e+06
25%    4.530599e+06
50%    4.892652e+06
75%    5.254133e+06
max    5.977815e+06

In [22]:
# Visualise sales_ytd by territory
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_ytd:Q", title="Sales Year To Date"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=["name", "CountryRegionCode", "group", "sales_ytd"]
).properties(
    title="Sales Year To Date by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [23]:
# Explore feature of interest: sales_ytd
df[["name", "CountryRegionCode", "group", "sales_ytd"]].sort_values(
    by="sales_ytd",
    ascending=False
)

             name CountryRegionCode    group     sales_ytd
2       Australia                AU  Pacific  5.977815e+06
3  United Kingdom                GB   Europe  5.012905e+06
0          France                FR   Europe  4.772398e+06
1         Germany                DE   Europe  3.805202e+06

In [24]:
feature_1_insights = """
The first feature explored is sales_ytd, which represents the current year-to-date sales for each sales territory.
This feature is important because it shows the current sales performance of each region and can help identify which territories are generating stronger business value.

The distribution shows that Australia has the highest sales_ytd at approximately 5.98 million, followed by the United Kingdom and France. Germany has the lowest sales_ytd at approximately 3.81 million.
The mean sales_ytd is around 4.89 million, with values ranging from about 3.81 million to 5.98 million. This indicates noticeable variation in current sales performance across the four territories.

There are no missing values in this feature, so no imputation is required. However, the dataset contains only four territories, so the feature should be interpreted carefully.
It is useful for descriptive analysis and may support later modelling as a regional context feature, but it would not be strong enough by itself for clustering.
"""

In [25]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

### B.3 Explore Feature of Interest `sales_last_year`

In [26]:
# Explore feature of interest: sales_last_year
feature_name = "sales_last_year"

df[[feature_name]].describe()

       sales_last_year
count     4.000000e+00
mean      1.904715e+06
std       5.196392e+05
min       1.307950e+06
25%       1.553855e+06
50%       1.957186e+06
75%       2.308047e+06
max       2.396540e+06

In [27]:
# Compare last year sales across territories
df[["name", "CountryRegionCode", "group", "sales_last_year"]].sort_values(
    by="sales_last_year",
    ascending=False
)

             name CountryRegionCode    group  sales_last_year
0          France                FR   Europe     2.396540e+06
2       Australia                AU  Pacific     2.278549e+06
3  United Kingdom                GB   Europe     1.635823e+06
1         Germany                DE   Europe     1.307950e+06

In [28]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_last_year:Q", title="Sales Last Year"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=["name", "CountryRegionCode", "group", "sales_last_year"]
).properties(
    title="Sales Last Year by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [29]:
feature_2_insights = """
The second feature explored is sales_last_year, which represents the sales achieved by each territory in the previous year.
This feature is useful because it provides historical context and allows current sales performance to be compared against past performance.

France had the highest sales_last_year at approximately 2.40 million, followed closely by Australia at approximately 2.28 million.
The United Kingdom and Germany had lower previous-year sales, with Germany being the lowest at approximately 1.31 million.
The mean sales_last_year is around 1.90 million, and the values range from about 1.31 million to 2.40 million.

There are no missing values in this feature, so no cleaning is required for missing data.
Compared with sales_ytd, the ranking of territories changed: Australia is highest in current year sales, while France was highest last year.
This suggests that sales performance has shifted over time, which makes sales_last_year useful for trend analysis and for creating derived features such as sales growth percentage."""

In [30]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

### B.4 Explore Feature of Interest `sales_ytd_vs_last_year_pct`

In [46]:
# Create and explore derived feature: sales_growth_pct
df["sales_ytd_vs_last_year_pct"] = (
    (df["sales_ytd"] - df["sales_last_year"]) / df["sales_last_year"]
) * 100

df[["name", "CountryRegionCode", "group", "sales_ytd", "sales_last_year", "sales_ytd_vs_last_year_pct"]].sort_values(
    by="sales_ytd_vs_last_year_pct",
    ascending=False
)

,name,CountryRegionCode,group,sales_ytd,sales_last_year,sales_ytd_vs_last_year_pct
3,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,206.445389
1,Germany,DE,Europe,3.805202e+06,1.307950e+06,190.928778
2,Australia,AU,Pacific,5.977815e+06,2.278549e+06,162.351829
0,France,FR,Europe,4.772398e+06,2.396540e+06,99.137039

In [47]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_ytd_vs_last_year_pct:Q", title="Sales YTD vs last year (%)"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=[
        "name",
        "CountryRegionCode",
        "group",
        alt.Tooltip("sales_ytd:Q", format=",.2f"),
        alt.Tooltip("sales_last_year:Q", format=",.2f"),
        alt.Tooltip("sales_ytd_vs_last_year_pct:Q", format=".2f")
    ]
).properties(
    title="Sales Growth Percentage by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [44]:
feature_3_insights = """
The third feature explored is sales_ytd_vs_last_year_pct, which was created from sales_ytd and sales_last_year. It measures the percentage difference between current year-to-date sales and last year's recorded sales for each territory.

This feature is useful as a directional territory performance indicator because it shows how current recorded sales compare with the previous year's sales baseline. However, it should not be interpreted as a precise year-on-year growth rate, because sales_ytd may represent only a partial current-year period while sales_last_year may represent the full previous year.

The results show that the United Kingdom has the highest sales_ytd_vs_last_year_pct, followed by Germany and Australia, while France has the lowest value among the four available territories. This suggests that current recorded sales are relatively stronger against last year's baseline in the United Kingdom and Germany than in France.

This feature has no missing values because sales_ytd and sales_last_year are complete for the available territory records. However, the result should be interpreted carefully because the sales_territory table contains only four territories. For the selected product-clustering use case, this feature is not suitable as a standalone clustering input, but it can provide useful regional context if territory information is later joined to transactional sales data.
"""

In [45]:
# Do not modify this code
print_tile(size="h3", key='feature_3_insights', value=feature_3_insights)

### Integration Analysis

In [33]:
# Load order-level fact data for contextual territory analysis
try:
    sales_order_header_df = pd.read_csv(at.folder_path / "sales_order_header.csv")
except Exception as e:
    print(e)

sales_order_header_df.head()

,sales_order_id,revision_number,status,online_order_flag,customer_id,sales_person_id,territory_id,currency_rate_id,order_date,due_date,ship_date,sales_order_number,account_number,sub_total,tax_amount,freight,total_due
0,1b9285b8-4501-4c92-adf7-ee74b4fa3d62,8.0,5.0,0.0,038a7b5e-5d15-4a1a-8305-e18131e402cc,28141e19-49e8-4090-9196-6e8f43b10de8,1e179cbb-7db9-4a66-aa94-e6fb9b3d613e,NaN,2011-05-30 22:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,SO43659,10-4020-000676,20565.6206,1971.5149,616.0984,23153.2339
1,b28eec58-f64d-4211-b604-bc9e801fb523,8.0,5.0,0.0,75c8fd92-2eb9-4223-b92c-f7c66751ed52,28141e19-49e8-4090-9196-6e8f43b10de8,1e179cbb-7db9-4a66-aa94-e6fb9b3d613e,NaN,2011-05-30 22:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,SO43660,10-4020-000117,1294.2529,124.2483,38.8276,1457.3288
2,664be852-4095-4495-887a-4fc24bb299e6,8.0,5.0,0.0,e5107fe5-b23a-46a4-8e49-bd195ef3b713,27d62980-8d18-4170-95a5-7f7bb9cada5a,c8b914d0-8c4c-498f-af9f-6954c90f45db,4.0,2011-05-30 22:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,SO43661,10-4020-000442,32726.4786,3153.7696,985.5530,36865.8012
3,a3a724bb-b604-40f8-b4d2-30621d551610,8.0,5.0,0.0,cb04c96c-e647-4fe1-9fbd-7010a3e3049f,27d62980-8d18-4170-95a5-7f7bb9cada5a,c8b914d0-8c4c-498f-af9f-6954c90f45db,4.0,2011-05-30 22:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,SO43662,10-4020-000227,28832.5289,2775.1646,867.2389,32474.9324
4,ed512092-ed9b-4614-b6d0-80a340884550,8.0,5.0,0.0,274634cb-6c91-4372-a64e-cc4277a73779,16eb6889-25f7-475a-9eff-92024a00fde9,5f568b38-d738-4b7a-a27b-bc975b9084a2,NaN,2011-05-30 22:00:00,2011-06-12 00:00:00,2011-06-07 00:00:00,SO43663,10-4020-000510,419.4589,40.2681,12.5838,472.3108

In [34]:
# Check the grain and join keys before merging
print("sales_territory rows:", len(df))
print("Unique territory_id in sales_territory:", df["territory_id"].nunique())
print("territory_id is unique in sales_territory:", df["territory_id"].is_unique)

print("\nsales_order_header rows:", len(sales_order_header_df))
print("Unique sales_order_id in sales_order_header:", sales_order_header_df["sales_order_id"].nunique())
print("sales_order_id is unique in sales_order_header:", sales_order_header_df["sales_order_id"].is_unique)

print("\nUnique territory_id in sales_order_header:", sales_order_header_df["territory_id"].nunique())

sales_territory rows: 4
Unique territory_id in sales_territory: 4
territory_id is unique in sales_territory: True

sales_order_header rows: 31465
Unique sales_order_id in sales_order_header: 31465
sales_order_id is unique in sales_order_header: True

Unique territory_id in sales_order_header: 10

In [35]:
# Join order-level sales activity to the territory dimension
territory_orders_df = sales_order_header_df.merge(
    df[["territory_id", "name", "CountryRegionCode", "group"]],
    on="territory_id",
    how="left",
    validate="many_to_one",
    indicator=True
)

# Check which order rows matched the available territory records
join_coverage = (
    territory_orders_df["_merge"]
    .value_counts(dropna=False)
    .rename_axis("join_status")
    .reset_index(name="order_rows")
)

join_coverage["percentage"] = (
    join_coverage["order_rows"] / len(territory_orders_df) * 100
).round(2)

join_coverage

  join_status  order_rows  percentage
0   left_only       16108       51.19
1        both       15357       48.81
2  right_only           0        0.00

In [36]:
# Keep orders that successfully matched to the available territory dimension rows
matched_territory_orders_df = territory_orders_df[
    territory_orders_df["_merge"] == "both"
].copy()

matched_territory_orders_df.shape

(15357, 21)

In [37]:
# Convert dates for summary analysis
matched_territory_orders_df["order_date"] = pd.to_datetime(
    matched_territory_orders_df["order_date"],
    errors="coerce"
)

# Summarise order activity for the available territories
territory_order_summary = (
    matched_territory_orders_df
    .groupby(["name", "CountryRegionCode", "group"], as_index=False)
    .agg(
        order_count=("sales_order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        total_sales_value=("total_due", "sum"),
        average_order_value=("total_due", "mean"),
        online_order_share=("online_order_flag", "mean"),
        first_order_date=("order_date", "min"),
        last_order_date=("order_date", "max")
    )
)

territory_order_summary["online_order_share"] = (
    territory_order_summary["online_order_share"] * 100
).round(2)

territory_order_summary.sort_values("total_sales_value", ascending=False)

,name,CountryRegionCode,group,order_count,customer_count,total_sales_value,average_order_value,online_order_share,first_order_date,last_order_date
0,Australia,AU,Pacific,6843,3625,1.181438e+07,1726.490734,98.17,2011-05-30 22:00:00,2014-06-29 22:00:00
3,United Kingdom,GB,Europe,3219,1951,8.574049e+06,2663.575243,94.16,2011-06-01 22:00:00,2014-06-29 22:00:00
1,France,FR,Europe,2672,1844,8.119749e+06,3038.828348,92.96,2011-05-30 22:00:00,2014-06-27 22:00:00
2,Germany,DE,Europe,2623,1812,5.479820e+06,2089.142042,94.70,2011-06-02 22:00:00,2014-06-29 22:00:00

In [38]:
alt.Chart(territory_order_summary).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("total_sales_value:Q", title="Total Order Value"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=[
        "name",
        "CountryRegionCode",
        "group",
        alt.Tooltip("total_sales_value:Q", format=",.2f"),
        alt.Tooltip("average_order_value:Q", format=",.2f"),
        "order_count"
    ]
).properties(
    title="Matched Total Order Value by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [48]:
territory_integration_insights = """
The sales_territory table was integrated with sales_order_header to understand whether the territory dimension can provide useful context for transaction-level analysis.

The grain of the two tables is different. sales_territory contains one row per territory, with 4 rows and 4 unique territory_id values. sales_order_header contains one row per sales order, with 31,465 rows and 31,465 unique sales_order_id values. Therefore, the appropriate join is a many-orders-to-one-territory join using territory_id.

The join coverage is incomplete. Only 15,357 sales order header rows, or 48.81%, match one of the four available territory records. The remaining 16,108 rows, or 51.19%, refer to territory_id values that are not present in the sales_territory extract. This means the available sales_territory table does not cover all order territories in the transactional data.

For the matched territories, Australia has the highest matched total order value and order volume. The United Kingdom and France also contribute substantial matched sales value, while Germany has the lowest matched total order value among the four available territories. France has a higher average order value than Australia and the United Kingdom, despite having fewer matched orders.

This integration analysis shows that sales_territory can provide useful regional context, but it should not be used as a primary clustering base. The table contains only four territory records and has incomplete coverage against sales_order_header. For the selected product-clustering use case, territory information may be considered only as optional contextual information if product-level regional features are later engineered from complete and reliable transaction joins.
"""

In [49]:
print_tile(size="h3", key='territory_integration_insights', value=territory_integration_insights)

### B.5 Explore Feature of Interest `cost_ytd` and `cost_last_year`

In [41]:
df[["cost_ytd", "cost_last_year"]].describe()

       cost_ytd  cost_last_year
count       4.0             4.0
mean        0.0             0.0
std         0.0             0.0
min         0.0             0.0
25%         0.0             0.0
50%         0.0             0.0
75%         0.0             0.0
max         0.0             0.0

In [42]:
feature_4_insights = """
The cost_ytd and cost_last_year columns were also reviewed, but both contain only zero values for all four territories.
Because these features have no variation, they do not provide useful analytical information and should not be used as clustering features.
"""

In [43]:
# Do not modify this code
print_tile(size="h3", key='feature_4_insights', value=feature_4_insights)