# **EDA Notebook**

---
## 0. Setup Environment

In [1]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 41.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [2]:
group_name = "group 24"
student_name = "Shameel Zeshan Khader Sheriff"
student_id = "26030371"

In [3]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [4]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [5]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [42]:
# No aditional package required

### 0.b Import Packages

In [6]:
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [8]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "sales_territory.csv")
except Exception as e:
  print(e)

In [19]:
# Preview the dataset
df

,territory_id,name,CountryRegionCode,group,sales_ytd,sales_last_year,cost_ytd,cost_last_year
0,0ad4c625-bb65-4376-8a41-0a65719b0db8,France,FR,Europe,4.772398e+06,2.396540e+06,0.0,0.0
1,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,Germany,DE,Europe,3.805202e+06,1.307950e+06,0.0,0.0
2,2ac923e9-3043-4f5e-bae0-ad28089bf187,Australia,AU,Pacific,5.977815e+06,2.278549e+06,0.0,0.0
3,e0e3bac4-790e-4617-84b3-be0c2bdb7070,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,0.0,0.0

In [11]:
df.shape

(4, 8)

In [12]:
df.size

32

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   territory_id       4 non-null      object
 1   name               4 non-null      object
 2   CountryRegionCode  4 non-null      object
 3   group              4 non-null      object
 4   sales_ytd          4 non-null      float64
 5   sales_last_year    4 non-null      float64
 6   cost_ytd           4 non-null      float64
 7   cost_last_year     4 non-null      float64
dtypes: float64(4), object(4)
memory usage: 388.0+ bytes

In [14]:
df.describe()

          sales_ytd  sales_last_year  cost_ytd  cost_last_year
count  4.000000e+00     4.000000e+00       4.0             4.0
mean   4.892080e+06     1.904715e+06       0.0             0.0
std    8.923837e+05     5.196392e+05       0.0             0.0
min    3.805202e+06     1.307950e+06       0.0             0.0
25%    4.530599e+06     1.553855e+06       0.0             0.0
50%    4.892652e+06     1.957186e+06       0.0             0.0
75%    5.254133e+06     2.308047e+06       0.0             0.0
max    5.977815e+06     2.396540e+06       0.0             0.0

In [15]:
df.isnull().sum().sort_values(ascending=False)

territory_id         0
name                 0
CountryRegionCode    0
group                0
sales_ytd            0
sales_last_year      0
cost_ytd             0
cost_last_year       0
dtype: int64

In [16]:
df.nunique().sort_values(ascending=False)

territory_id         4
name                 4
CountryRegionCode    4
sales_ytd            4
sales_last_year      4
group                2
cost_ytd             1
cost_last_year       1
dtype: int64

### B.1 Explore Dataset

In [9]:
# Basic dataset overview
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

print("\nDataset information:")
display(df.info())

print("\nMissing values by column:")
display(df.isna().sum().to_frame("missing_values"))

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nSummary statistics:")
display(df.describe(include="all").T)

Dataset shape: (4, 8)

Column names:
['territory_id', 'name', 'CountryRegionCode', 'group', 'sales_ytd', 'sales_last_year', 'cost_ytd', 'cost_last_year']

First 5 rows:

,territory_id,name,CountryRegionCode,group,sales_ytd,sales_last_year,cost_ytd,cost_last_year
0,0ad4c625-bb65-4376-8a41-0a65719b0db8,France,FR,Europe,4.772398e+06,2.396540e+06,0.0,0.0
1,25d73ad2-9e13-410b-8b0d-5f26e2b9e4f2,Germany,DE,Europe,3.805202e+06,1.307950e+06,0.0,0.0
2,2ac923e9-3043-4f5e-bae0-ad28089bf187,Australia,AU,Pacific,5.977815e+06,2.278549e+06,0.0,0.0
3,e0e3bac4-790e-4617-84b3-be0c2bdb7070,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,0.0,0.0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   territory_id       4 non-null      object
 1   name               4 non-null      object
 2   CountryRegionCode  4 non-null      object
 3   group              4 non-null      object
 4   sales_ytd          4 non-null      float64
 5   sales_last_year    4 non-null      float64
 6   cost_ytd           4 non-null      float64
 7   cost_last_year     4 non-null      float64
dtypes: float64(4), object(4)
memory usage: 388.0+ bytes

None

Missing values by column:

                   missing_values
territory_id                    0
name                            0
CountryRegionCode               0
group                           0
sales_ytd                       0
sales_last_year                 0
cost_ytd                        0
cost_last_year                  0

Duplicate rows:
0

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
territory_id,4,4,0ad4c625-bb65-4376-8a41-0a65719b0db8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
name,4,4,France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CountryRegionCode,4,4,FR,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
group,4,2,Europe,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sales_ytd,4.0,NaN,NaN,NaN,4892080.23415,892383.664461,3805202.3478,4530599.3178,4892651.8367,5254132.75305,5977814.9154
sales_last_year,4.0,NaN,NaN,NaN,1904715.481525,519639.248459,1307949.7917,1553854.99545,1957186.18715,2308046.673225,2396539.7601
cost_ytd,4.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cost_last_year,4.0,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
dataset_insights = """
provide a detailed analysis on the dataset, its dimensions, information, issues, ...

The sales_territory dataset contains 4 rows and 8 columns, where each row represents one sales territory.
The dataset includes territory identifiers, territory names, country or region codes, territory group, current year sales, last year sales, and cost-related fields.

The dataset is very small, so it is more useful as a descriptive or supporting table rather than a standalone modelling dataset.
There are no missing values and no duplicate rows, which means the dataset is clean from a basic data quality perspective.
The categorical columns are territory_id, name, CountryRegionCode, and group, while the numerical columns are sales_ytd, sales_last_year, cost_ytd, and cost_last_year.

The sales_ytd and sales_last_year columns show variation across territories, so they can provide useful information about regional sales performance.
However, cost_ytd and cost_last_year are both zero for all territories, meaning these fields have no variation and are not useful for modelling or clustering.
Overall, this dataset can help understand geographic sales context, but it should be combined with other datasets such as sales orders, customers, products, and offers for a stronger clustering model.
"""

In [18]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `sales_ytd`

In [21]:
# Explore feature of interest: sales_ytd
feature_name = "sales_ytd"

df[[feature_name]].describe()

          sales_ytd
count  4.000000e+00
mean   4.892080e+06
std    8.923837e+05
min    3.805202e+06
25%    4.530599e+06
50%    4.892652e+06
75%    5.254133e+06
max    5.977815e+06

In [22]:
# Visualise sales_ytd by territory
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_ytd:Q", title="Sales Year To Date"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=["name", "CountryRegionCode", "group", "sales_ytd"]
).properties(
    title="Sales Year To Date by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [23]:
# Explore feature of interest: sales_ytd
df[["name", "CountryRegionCode", "group", "sales_ytd"]].sort_values(
    by="sales_ytd",
    ascending=False
)

             name CountryRegionCode    group     sales_ytd
2       Australia                AU  Pacific  5.977815e+06
3  United Kingdom                GB   Europe  5.012905e+06
0          France                FR   Europe  4.772398e+06
1         Germany                DE   Europe  3.805202e+06

In [25]:
feature_1_insights = """
The first feature explored is sales_ytd, which represents the current year-to-date sales for each sales territory.
This feature is important because it shows the current sales performance of each region and can help identify which territories are generating stronger business value.

The distribution shows that Australia has the highest sales_ytd at approximately 5.98 million, followed by the United Kingdom and France. Germany has the lowest sales_ytd at approximately 3.81 million.
The mean sales_ytd is around 4.89 million, with values ranging from about 3.81 million to 5.98 million. This indicates noticeable variation in current sales performance across the four territories.

There are no missing values in this feature, so no imputation is required. However, the dataset contains only four territories, so the feature should be interpreted carefully.
It is useful for descriptive analysis and may support later modelling as a regional context feature, but it would not be strong enough by itself for clustering.
"""

In [26]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

### B.3 Explore Feature of Interest `sales_last_year`

In [27]:
# Explore feature of interest: sales_last_year
feature_name = "sales_last_year"

df[[feature_name]].describe()

       sales_last_year
count     4.000000e+00
mean      1.904715e+06
std       5.196392e+05
min       1.307950e+06
25%       1.553855e+06
50%       1.957186e+06
75%       2.308047e+06
max       2.396540e+06

In [28]:
# Compare last year sales across territories
df[["name", "CountryRegionCode", "group", "sales_last_year"]].sort_values(
    by="sales_last_year",
    ascending=False
)

             name CountryRegionCode    group  sales_last_year
0          France                FR   Europe     2.396540e+06
2       Australia                AU  Pacific     2.278549e+06
3  United Kingdom                GB   Europe     1.635823e+06
1         Germany                DE   Europe     1.307950e+06

In [29]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_last_year:Q", title="Sales Last Year"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=["name", "CountryRegionCode", "group", "sales_last_year"]
).properties(
    title="Sales Last Year by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [30]:
feature_2_insights = """
The second feature explored is sales_last_year, which represents the sales achieved by each territory in the previous year.
This feature is useful because it provides historical context and allows current sales performance to be compared against past performance.

France had the highest sales_last_year at approximately 2.40 million, followed closely by Australia at approximately 2.28 million.
The United Kingdom and Germany had lower previous-year sales, with Germany being the lowest at approximately 1.31 million.
The mean sales_last_year is around 1.90 million, and the values range from about 1.31 million to 2.40 million.

There are no missing values in this feature, so no cleaning is required for missing data.
Compared with sales_ytd, the ranking of territories changed: Australia is highest in current year sales, while France was highest last year.
This suggests that sales performance has shifted over time, which makes sales_last_year useful for trend analysis and for creating derived features such as sales growth percentage."""

In [31]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

### B.4 Explore Feature of Interest `sales_growth_pct`

In [32]:
# Create and explore derived feature: sales_growth_pct
df["sales_growth_pct"] = (
    (df["sales_ytd"] - df["sales_last_year"]) / df["sales_last_year"]
) * 100

df[["name", "CountryRegionCode", "group", "sales_ytd", "sales_last_year", "sales_growth_pct"]].sort_values(
    by="sales_growth_pct",
    ascending=False
)

,name,CountryRegionCode,group,sales_ytd,sales_last_year,sales_growth_pct
3,United Kingdom,GB,Europe,5.012905e+06,1.635823e+06,206.445389
1,Germany,DE,Europe,3.805202e+06,1.307950e+06,190.928778
2,Australia,AU,Pacific,5.977815e+06,2.278549e+06,162.351829
0,France,FR,Europe,4.772398e+06,2.396540e+06,99.137039

In [33]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("name:N", title="Sales Territory", sort="-y"),
    y=alt.Y("sales_growth_pct:Q", title="Sales Growth (%)"),
    color=alt.Color("group:N", title="Territory Group"),
    tooltip=[
        "name",
        "CountryRegionCode",
        "group",
        alt.Tooltip("sales_ytd:Q", format=",.2f"),
        alt.Tooltip("sales_last_year:Q", format=",.2f"),
        alt.Tooltip("sales_growth_pct:Q", format=".2f")
    ]
).properties(
    title="Sales Growth Percentage by Territory",
    width=500,
    height=300
)

alt.Chart(...)

In [36]:
feature_3_insights = """
The third feature explored is sales_growth_pct, which was created from sales_ytd and sales_last_year.
It measures the percentage change between current year-to-date sales and last year sales for each territory.
This derived feature is useful because it gives more insight than looking at current or previous sales separately.

The United Kingdom has the highest sales growth percentage at approximately 206.45%, followed by Germany at approximately 190.93%.
Australia also shows strong growth at approximately 162.35%, while France has the lowest growth at approximately 99.14%.
Although France had the highest sales last year, its growth rate is the lowest among the four territories, while the United Kingdom shows the strongest improvement.

This feature has no missing values because both sales_ytd and sales_last_year are complete and non-zero.
However, the result should be interpreted carefully because the dataset contains only four territories.
For clustering, sales_growth_pct could be useful as a regional context feature, but it should be combined with other customer, product, sales, cost, and promotion features to create meaningful segments.
"""

In [37]:
# Do not modify this code
print_tile(size="h3", key='feature_3_insights', value=feature_3_insights)

### B.5 Explore Feature of Interest `cost_ytd` and `cost_last_year`

In [38]:
df[["cost_ytd", "cost_last_year"]].describe()

       cost_ytd  cost_last_year
count       4.0             4.0
mean        0.0             0.0
std         0.0             0.0
min         0.0             0.0
25%         0.0             0.0
50%         0.0             0.0
75%         0.0             0.0
max         0.0             0.0

In [40]:
feature_4_insights = """
The cost_ytd and cost_last_year columns were also reviewed, but both contain only zero values for all four territories.
Because these features have no variation, they do not provide useful analytical information and should not be used as clustering features.
"""

In [41]:
# Do not modify this code
print_tile(size="h3", key='feature_4_insights', value=feature_4_insights)