# **EDA Notebook**

---
## 0. Setup Environment

In [1]:
# DO NOT MODIFY THE CODE IN THIS CELL
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT3",
)
at.run()

import warnings
warnings.simplefilter(action='ignore')

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.9/12.9 MB 48.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 79.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
hdbscan 0.8.42 requires scikit-learn>=1.6, but you have scikit-learn 1.5.2 which is incompatible.
Mounted at /content/gdrive

You can now save your data files in: /content/gdrive/MyDrive/36106/assignment/AT3/data

---
## Student Information

In [2]:
group_name = "group 24"
student_name = "Shameel Zeshan Khader Sheriff"
student_id = "26030371"

In [3]:
# Do not modify this code
print_tile(size="h1", key='group_name', value=group_name)

In [4]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [5]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

---
## 0. Python Packages

### 0.a Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [6]:
# No aditional package required

### 0.b Import Packages

In [7]:
import pandas as pd
import altair as alt

---
## B. Data Understanding

In [8]:
# Do not modify this code
try:
  df = pd.read_csv(at.folder_path / "special_offer.csv")
except Exception as e:
  print(e)

### B.1 Explore Dataset

In [9]:
# Preview the dataset
df.head()

,special_offer_id,min_quantity,max_quantity,description,discount_pct,type,category,start_date,end_date
0,a1444fcd-4b51-4227-94cf-b13c1a2a6281,0.0,NaN,No Discount,0.00,No Discount,No Discount,2011-05-01 00:00:00,2014-11-30 00:00:00
1,df7c9acd-bc0c-4ab0-93ec-064e2b93af0d,11.0,14.0,Volume Discount 11 to 14,0.02,Volume Discount,Reseller,2011-05-31 00:00:00,2014-05-30 00:00:00
2,da53c22d-5867-4110-b1d0-8d84bea95ab5,15.0,24.0,Volume Discount 15 to 24,0.05,Volume Discount,Reseller,2011-05-31 00:00:00,2014-05-30 00:00:00
3,aec729b3-e92e-4f2c-971c-4c5d426a99b9,25.0,40.0,Volume Discount 25 to 40,0.10,Volume Discount,Reseller,2011-05-31 00:00:00,2014-05-30 00:00:00
4,41f713bd-c29a-4ab1-ae06-dbb51ec03ec0,41.0,60.0,Volume Discount 41 to 60,0.15,Volume Discount,Reseller,2011-05-31 00:00:00,2014-05-30 00:00:00

In [10]:
df.shape

(16, 9)

In [11]:
df.size

144

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   special_offer_id  16 non-null     object
 1   min_quantity      16 non-null     float64
 2   max_quantity      4 non-null      float64
 3   description       16 non-null     object
 4   discount_pct      16 non-null     float64
 5   type              16 non-null     object
 6   category          16 non-null     object
 7   start_date        16 non-null     object
 8   end_date          16 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.3+ KB

In [13]:
df.describe()

       min_quantity  max_quantity  discount_pct
count     16.000000      4.000000     16.000000
mean       9.562500     34.500000      0.220000
std       18.092241     20.091458      0.161452
min        0.000000     14.000000      0.000000
25%        0.000000     21.500000      0.100000
50%        0.000000     32.000000      0.175000
75%       12.000000     45.000000      0.350000
max       61.000000     60.000000      0.500000

In [14]:
df.isnull().sum().sort_values(ascending=False)

max_quantity        12
special_offer_id     0
min_quantity         0
description          0
discount_pct         0
type                 0
category             0
start_date           0
end_date             0
dtype: int64

In [15]:
df.nunique().sort_values(ascending=False)

special_offer_id    16
description         16
discount_pct        10
end_date            10
start_date           8
type                 6
min_quantity         6
max_quantity         4
category             3
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
dataset_insights = """
The special_offer dataset contains 16 rows and 9 columns, where each row represents a different promotional offer or discount rule.
The dataset includes offer identifiers, minimum and maximum quantity conditions, offer descriptions, discount percentages, offer type, category, start date, and end date.

The dataset is small but useful for understanding the retailer's promotion strategy. There are no duplicate rows, and most columns have complete values.
The only column with missing values is max_quantity, with 12 missing values out of 16 rows. This is likely meaningful rather than an error, because some offers may not have an upper quantity limit.
Therefore, missing max_quantity values should be handled carefully rather than simply removed.

The discount_pct column ranges from 0.00 to 0.50, meaning discounts vary from no discount to 50%.
The min_quantity column ranges from 0 to 61, showing that some offers apply immediately while others require a minimum purchase quantity.
The dataset contains 6 offer types and 3 categories, which suggests different promotional strategies such as no discount, volume discount, seasonal discount, and customer-specific offers.

For clustering, this dataset can help create promotion-related features such as maximum discount percentage, average discount percentage, discount type, and whether a product or customer is associated with promotional purchases.
"""

In [18]:
# Do not modify this code
print_tile(size="h3", key='dataset_insights', value=dataset_insights)

### B.2 Explore Feature of Interest `discount_pct`

In [19]:
# Explore feature of interest: discount_pct
feature_name = "discount_pct"

df[[feature_name]].describe()

       discount_pct
count     16.000000
mean       0.220000
std        0.161452
min        0.000000
25%        0.100000
50%        0.175000
75%        0.350000
max        0.500000

In [20]:
# Sort offers by discount percentage
df[["description", "type", "category", "min_quantity", "max_quantity", "discount_pct"]].sort_values(
    by="discount_pct",
    ascending=False
)

,description,type,category,min_quantity,max_quantity,discount_pct
14,Half-Price Pedal Sale,Seasonal Discount,Customer,0.0,NaN,0.50
9,Mountain Tire Sale,Excess Inventory,Customer,0.0,NaN,0.50
15,Mountain-500 Silver Clearance Sale,Discontinued Product,Reseller,0.0,NaN,0.40
6,Mountain-100 Clearance Sale,Discontinued Product,Reseller,0.0,NaN,0.35
11,LL Road Frame Sale,Excess Inventory,Reseller,0.0,NaN,0.35
8,Road-650 Overstock,Excess Inventory,Reseller,0.0,NaN,0.30
13,Touring-1000 Promotion,New Product,Reseller,0.0,NaN,0.20
5,Volume Discount over 60,Volume Discount,Reseller,61.0,NaN,0.20
10,Sport Helmet Discount-2003,Seasonal Discount,Reseller,0.0,NaN,0.15
4,Volume Discount 41 to 60,Volume Discount,Reseller,41.0,60.0,0.15
12,Touring-3000 Promotion,New Product,Reseller,0.0,NaN,0.15
3,Volume Discount 25 to 40,Volume Discount,Reseller,25.0,40.0,0.10
7,Sport Helmet Discount-2002,Seasonal Discount,Reseller,0.0,NaN,0.10
2,Volume Discount 15 to 24,Volume Discount,Reseller,15.0,24.0,0.05
1,Volume Discount 11 to 14,Volume Discount,Reseller,11.0,14.0,0.02
0,No Discount,No Discount,No Discount,0.0,NaN,0.00

In [21]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("description:N", title="Special Offer", sort="-y"),
    y=alt.Y("discount_pct:Q", title="Discount Percentage"),
    color=alt.Color("category:N", title="Offer Category"),
    tooltip=[
        "description",
        "type",
        "category",
        alt.Tooltip("min_quantity:Q", title="Minimum Quantity"),
        alt.Tooltip("max_quantity:Q", title="Maximum Quantity"),
        alt.Tooltip("discount_pct:Q", format=".2f", title="Discount Percentage")
    ]
).properties(
    title="Discount Percentage by Special Offer",
    width=650,
    height=350
)

alt.Chart(...)

In [22]:
feature_1_insights = """
The first feature explored is discount_pct, which represents the discount percentage applied by each special offer.
This feature is important because discount depth can influence customer purchasing behaviour, product demand, and promotion sensitivity.

The discount_pct values range from 0.00 to 0.50, meaning the offers range from no discount to a maximum discount of 50%.
The average discount is 0.22, or 22%, while the median is 0.175, or 17.5%.
The highest discounts are linked to offers such as Half-Price Pedal Sale and Mountain Tire Sale, both at 50%.
There is also one No Discount offer with a discount value of 0.00.

The chart shows that customer-focused offers have some of the highest discount percentages, while reseller offers cover a wider range of discounts from low volume discounts to clearance and overstock offers.
There are no missing values in discount_pct, so no imputation is required for this feature.
For clustering, discount_pct can help create promotion-related features such as maximum discount received, average discount exposure, and discount sensitivity."""

In [23]:
# Do not modify this code
print_tile(size="h3", key='feature_1_insights', value=feature_1_insights)

### B.3 Explore Feature of Interest `type`

In [24]:
# Explore feature of interest: type
feature_name = "type"

df[feature_name].value_counts()

type
Volume Discount         5
Seasonal Discount       3
Excess Inventory        3
Discontinued Product    2
New Product             2
No Discount             1
Name: count, dtype: int64

In [25]:
# Compare offer types with discount statistics
df.groupby("type").agg(
    offer_count=("special_offer_id", "count"),
    avg_discount_pct=("discount_pct", "mean"),
    min_discount_pct=("discount_pct", "min"),
    max_discount_pct=("discount_pct", "max"),
    avg_min_quantity=("min_quantity", "mean")
).sort_values(by="offer_count", ascending=False)

,offer_count,avg_discount_pct,min_discount_pct,max_discount_pct,avg_min_quantity
type,,,,,
Volume Discount,5,0.104000,0.02,0.2,30.6
Excess Inventory,3,0.383333,0.30,0.5,0.0
Seasonal Discount,3,0.250000,0.10,0.5,0.0
Discontinued Product,2,0.375000,0.35,0.4,0.0
New Product,2,0.175000,0.15,0.2,0.0
No Discount,1,0.000000,0.00,0.0,0.0

In [26]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("type:N", title="Offer Type", sort="-y"),
    y=alt.Y("count():Q", title="Number of Offers"),
    color=alt.Color("type:N", legend=None),
    tooltip=["type", "count()"]
).properties(
    title="Number of Special Offers by Type",
    width=500,
    height=300
)

alt.Chart(...)

In [27]:
feature_2_insights = """
The second feature explored is type, which describes the type of promotion used for each special offer.
This feature is important because it shows the retailer's promotion strategy and helps explain why different discounts may exist.

The most common offer type is Volume Discount, with 5 offers. Seasonal Discount and Excess Inventory each appear 3 times, while Discontinued Product and New Product each appear 2 times.
There is also 1 No Discount offer. This shows that the retailer uses a mix of promotional strategies, including quantity-based discounts, seasonal sales, inventory clearance, discontinued product discounts, and new product promotions.

The grouped statistics show that Excess Inventory has the highest average discount at about 38.33%, followed by Discontinued Product at 37.5%.
Volume Discount offers are more frequent but have a lower average discount of about 10.4%, and they also have higher minimum quantity requirements.
This suggests that different offer types serve different business purposes: some are used to clear stock, while others encourage larger purchases.

There are no missing values in the type column. For clustering, this feature can support promotion-related variables such as offer frequency by type or whether customers/products are mainly exposed to clearance, seasonal, or volume-based offers."""

In [28]:
# Do not modify this code
print_tile(size="h3", key='feature_2_insights', value=feature_2_insights)

### B.4 Explore Feature of Interest `category`

In [29]:
# Explore feature of interest: category
feature_name = "category"

df[feature_name].value_counts()

category
Reseller       13
Customer        2
No Discount     1
Name: count, dtype: int64

In [30]:
# Compare offer categories with discount statistics
df.groupby("category").agg(
    offer_count=("special_offer_id", "count"),
    avg_discount_pct=("discount_pct", "mean"),
    min_discount_pct=("discount_pct", "min"),
    max_discount_pct=("discount_pct", "max"),
    avg_min_quantity=("min_quantity", "mean")
).sort_values(by="offer_count", ascending=False)

,offer_count,avg_discount_pct,min_discount_pct,max_discount_pct,avg_min_quantity
category,,,,,
Reseller,13,0.193846,0.02,0.4,11.769231
Customer,2,0.500000,0.50,0.5,0.000000
No Discount,1,0.000000,0.00,0.0,0.000000

In [31]:
alt.Chart(df).mark_bar().encode(
    x=alt.X("category:N", title="Offer Category", sort="-y"),
    y=alt.Y("count():Q", title="Number of Offers"),
    color=alt.Color("category:N", legend=None),
    tooltip=["category", "count()"]
).properties(
    title="Number of Special Offers by Category",
    width=450,
    height=300
)

alt.Chart(...)

In [32]:
feature_3_insights = """
The third feature explored is category, which identifies the target category of each special offer.
This feature is useful because it shows whether promotions are mainly aimed at resellers, customers, or no-discount situations.

The majority of offers are in the Reseller category, with 13 out of 16 offers.
Customer offers appear only 2 times, and there is 1 No Discount category.
This shows that the retailer's special offer strategy is mainly focused on reseller promotions rather than direct customer promotions.

The grouped statistics show that Customer offers have the highest average discount percentage at 50%, although there are only two customer offers.
Reseller offers have a lower average discount of about 19.38%, but they are much more frequent and include a wider range of discount levels from 2% to 40%.
The Reseller category also has a higher average minimum quantity, which suggests that reseller promotions are often designed to encourage larger purchase volumes.

There are no missing values in the category column.
For clustering, this feature can help create promotion exposure features, such as whether products or customers are mainly associated with reseller discounts, customer discounts, or no-discount purchases."""

In [33]:
# Do not modify this code
print_tile(size="h3", key='feature_3_insights', value=feature_3_insights)

### Integration Analysis: Special Offer Usage in Sales Order Lines

In [34]:
# Load order-line fact data for contextual special offer analysis
try:
    sales_order_detail_df = pd.read_csv(at.folder_path / "sales_order_detail.csv")
except Exception as e:
    print(e)

sales_order_detail_df.head()

,sales_order_id,sales_order_detail_id,order_quantity,product_id,special_offer_id,unit_price,unit_price_discount,line_total
0,0fbc9d71-4176-4c77-92c6-d7ede2a9ce33,354.0,1.0,6cc3d977-da73-4856-b1ca-8a2f0b57b60b,a1444fcd-4b51-4227-94cf-b13c1a2a6281,3399.99,0.0,3399.99
1,18609f9d-aedc-4665-bbc8-5d7a99599915,357.0,1.0,6cc3d977-da73-4856-b1ca-8a2f0b57b60b,a1444fcd-4b51-4227-94cf-b13c1a2a6281,3399.99,0.0,3399.99
2,0570389a-6bfa-45c2-85a4-36784fa7b5b1,359.0,1.0,41b7b226-20ea-488a-b519-b4ca65d4a64e,a1444fcd-4b51-4227-94cf-b13c1a2a6281,3578.27,0.0,3578.27
3,b48cdf2f-270a-41d0-9cde-36616fecd302,360.0,1.0,de8b1961-ea0e-4639-9482-7f71b3ed07d8,a1444fcd-4b51-4227-94cf-b13c1a2a6281,3374.99,0.0,3374.99
4,03533644-6a12-499b-9726-aaa1088c56a5,361.0,1.0,a16ed5b0-74c7-4812-adea-04b4abfd72c7,a1444fcd-4b51-4227-94cf-b13c1a2a6281,3399.99,0.0,3399.99

In [35]:
# Check table levels and join keys before merging
print("special_offer rows:", len(df))
print("Unique special_offer_id in special_offer:", df["special_offer_id"].nunique())
print("special_offer_id is unique in special_offer:", df["special_offer_id"].is_unique)

print("\nsales_order_detail rows:", len(sales_order_detail_df))
print("Unique sales_order_detail_id in sales_order_detail:", sales_order_detail_df["sales_order_detail_id"].nunique())
print("sales_order_detail_id is unique in sales_order_detail:", sales_order_detail_df["sales_order_detail_id"].is_unique)

print("\nUnique special_offer_id used in sales_order_detail:", sales_order_detail_df["special_offer_id"].nunique())

special_offer rows: 16
Unique special_offer_id in special_offer: 16
special_offer_id is unique in special_offer: True

sales_order_detail rows: 42100
Unique sales_order_detail_id in sales_order_detail: 42100
sales_order_detail_id is unique in sales_order_detail: True

Unique special_offer_id used in sales_order_detail: 10

In [36]:
# Join order-line sales activity to special offer details
offer_sales_df = sales_order_detail_df.merge(
    df[
        [
            "special_offer_id",
            "description",
            "type",
            "category",
            "discount_pct",
            "min_quantity",
            "max_quantity"
        ]
    ],
    on="special_offer_id",
    how="left",
    validate="many_to_one",
    indicator=True
)

join_coverage = (
    offer_sales_df["_merge"]
    .value_counts(dropna=False)
    .rename_axis("join_status")
    .reset_index(name="order_line_rows")
)

join_coverage["percentage"] = (
    join_coverage["order_line_rows"] / len(offer_sales_df) * 100
).round(2)

join_coverage

  join_status  order_line_rows  percentage
0        both            42100       100.0
1   left_only                0         0.0
2  right_only                0         0.0

In [45]:
# Summarise how offers appear in order-line transactions
offer_usage_summary = (
    offer_sales_df
    .groupby(
        ["description", "type", "category", "discount_pct"],
        as_index=False
    )
    .agg(
        order_line_count=("sales_order_detail_id", "nunique"),
        order_count=("sales_order_id", "nunique"),
        product_count=("product_id", "nunique"),
        total_quantity=("order_quantity", "sum"),
        total_line_value=("line_total", "sum")
    )
)


offer_usage_summary.sort_values("order_line_count", ascending=False)

,description,type,category,discount_pct,order_line_count,order_count,product_count,total_quantity,total_line_value
1,No Discount,No Discount,No Discount,0.00,40081,14988,254,62288.0,2.782087e+07
7,Volume Discount 11 to 14,Volume Discount,Reseller,0.02,1465,1245,74,4912.0,1.930640e+06
6,Touring-3000 Promotion,New Product,Reseller,0.15,225,56,10,690.0,2.014255e+05
8,Volume Discount 15 to 24,Volume Discount,Reseller,0.05,148,75,33,2590.0,2.572530e+05
5,Touring-1000 Promotion,New Product,Reseller,0.20,102,44,4,330.0,2.582425e+05
0,Mountain-500 Silver Clearance Sale,Discontinued Product,Reseller,0.40,33,13,5,74.0,5.017111e+03
4,Sport Helmet Discount-2003,Seasonal Discount,Reseller,0.15,20,7,3,222.0,2.971176e+03
3,Sport Helmet Discount-2002,Seasonal Discount,Reseller,0.10,12,4,3,67.0,1.014373e+03
9,Volume Discount 25 to 40,Volume Discount,Reseller,0.10,8,7,4,222.0,8.020674e+03
2,Road-650 Overstock,Excess Inventory,Reseller,0.30,6,6,1,46.0,7.563683e+03

In [38]:
alt.Chart(offer_usage_summary).mark_bar().encode(
    x=alt.X("description:N", title="Special Offer", sort="-y"),
    y=alt.Y("order_line_count:Q", title="Number of Order Lines"),
    color=alt.Color("type:N", title="Offer Type"),
    tooltip=[
        "description",
        "type",
        "category",
        alt.Tooltip("discount_pct:Q", format=".2f", title="Offer Discount"),
        "order_line_count",
        "order_count",
        "product_count",
        alt.Tooltip("total_line_value:Q", format=",.2f")
    ]
).properties(
    title="Special Offer Usage in Sales Order Lines",
    width=700,
    height=350
)

alt.Chart(...)

In [46]:
# Visualise promotional offer usage excluding the dominant No Discount rule
promotional_offer_usage = offer_usage_summary[
    offer_usage_summary["description"] != "No Discount"
].copy()

alt.Chart(promotional_offer_usage).mark_bar().encode(
    x=alt.X("description:N", title="Promotional Offer", sort="-y"),
    y=alt.Y("order_line_count:Q", title="Number of Order Lines"),
    color=alt.Color("type:N", title="Offer Type"),
    tooltip=[
        "description",
        "type",
        "category",
        alt.Tooltip("discount_pct:Q", format=".2f", title="Offer Rule Discount"),
        "order_line_count",
        "order_count",
        "product_count",
        alt.Tooltip("total_line_value:Q", format=",.2f")
    ]
).properties(
    title="Promotional Offer Usage in Sales Order Lines",
    width=700,
    height=350
)

alt.Chart(...)

In [ ]:
special_offer_usage_insights = """
Because special_offer is a small offer-level dimension table, it was linked to sales_order_detail to examine how offer rules appear in actual order-line transactions.

The grain changes across the join. special_offer has one row per offer rule, supported by 16 rows and 16 unique special_offer_id values. sales_order_detail has one row per sales order line, supported by 42,100 rows and 42,100 unique sales_order_detail_id values. Therefore, this is a many-order-lines-to-one-offer join using special_offer_id.

The join coverage is complete: all 42,100 order lines matched to a record in the special_offer table. However, only 10 of the 16 available special offers appear in sales_order_detail, showing that not every offer rule in the dimension is used in the observed transactional extract.

The offer usage distribution is highly imbalanced. The No Discount rule is linked to 40,081 order lines, which is about 95.2% of all sales order detail rows. Among promotional offers, Volume Discount 11 to 14 is the most frequently linked offer, followed by Touring-3000 Promotion and Volume Discount 15 to 24.

Because the No Discount rule dominates the full usage chart, a second view excluding No Discount was used to compare the relative usage of promotional offer rules more clearly. This second view shows that promotional activity is not evenly distributed across offer types: volume discounts and selected new-product promotions appear much more frequently in the observed order lines than several clearance, seasonal, and excess-inventory offers.

The joined analysis shows how special offer rules appear in observed order-line transactions. The full distribution is dominated by the No Discount rule, while promotional offers are much less frequent. This means promotion-related modelling features may still be useful, but their imbalance should be considered during later product-level feature engineering and cluster interpretation.

This analysis supports the selected product segmentation use case because offer type, discount depth, and promotion exposure may help distinguish products that sell mainly without promotional offers from products that are more promotion-linked.
"""

In [48]:
print_tile(
    size="h3",
    key="special_offer_usage_insights",
    value=special_offer_usage_insights
)